# Generated by Django 3.1.3 on 2020-12-23 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_title', models.CharField(max_length=512)),
                ('conference', models.CharField(max_length=512)),
                ('arxiv_id', models.CharField(max_length=32)),
                ('mag_id', models.CharField(max_length=12)),
                ('citation_count', models.IntegerField()),
                ('publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WriteEntity',
            fields=[
                ('write_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esra_backend.author')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esra_backend.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('citation_id', models.AutoField(primary_key=True, serialize=False)),
                ('cited_paper_id', models.IntegerField()),
                ('cite_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esra_backend.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('affiliation_id', models.AutoField(primary_key=True, serialize=False)),
                ('affiliation_name', models.CharField(max_length=256)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esra_backend.author')),
            ],
        ),
    ]
