# Generated by Django 3.1.3 on 2020-12-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_title', models.CharField(max_length=512)),
                ('conference', models.CharField(max_length=512)),
                ('arxiv_id', models.CharField(max_length=32)),
                ('mag_id', models.CharField(max_length=12)),
                ('citation_count', models.IntegerField()),
                ('publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('cite_paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='esra_backend.paper')),
                ('cited_paper_id', models.IntegerField()),
            ],
            options={
                'unique_together': {('cite_paper_id', 'cited_paper_id')},
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='esra_backend.author')),
                ('affiliation_name', models.CharField(max_length=256)),
            ],
            options={
                'unique_together': {('author_id', 'affiliation_name')},
            },
        ),
        migrations.CreateModel(
            name='WriteEntity',
            fields=[
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='esra_backend.paper')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esra_backend.author')),
            ],
            options={
                'unique_together': {('paper_id', 'author_id')},
            },
        ),
    ]
