# Generated by Django 2.2.5 on 2020-12-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esra_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='abstract',
            field=models.TextField(null=True),
        ),
    ]
