# Generated by Django 3.1.3 on 2020-12-23 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esra_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeentity',
            name='id',
        ),
        migrations.AlterField(
            model_name='writeentity',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='esra_backend.paper'),
        ),
    ]
