# Generated by Django 3.1.3 on 2020-12-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esra_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliation',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='citation',
            old_name='cite_paper_id',
            new_name='cite_paper',
        ),
        migrations.RenameField(
            model_name='writeentity',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='writeentity',
            old_name='paper_id',
            new_name='paper',
        ),
    ]
