# Generated by Django 2.2.5 on 2020-12-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esra_backend', '0002_paper_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeentity',
            name='author',
        ),
        migrations.RemoveField(
            model_name='writeentity',
            name='paper',
        ),
        migrations.AddField(
            model_name='author',
            name='paper',
            field=models.ManyToManyField(to='esra_backend.Paper'),
        ),
        migrations.AddField(
            model_name='paper',
            name='cite_to',
            field=models.ManyToManyField(blank=True, null=True, to='esra_backend.Paper'),
        ),
        migrations.RemoveField(
            model_name='affiliation',
            name='author',
        ),
        migrations.AddField(
            model_name='affiliation',
            name='author',
            field=models.ManyToManyField(to='esra_backend.Author'),
        ),
        migrations.DeleteModel(
            name='Citation',
        ),
        migrations.DeleteModel(
            name='WriteEntity',
        ),
    ]
