# Generated by Django 2.2.5 on 2020-12-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esra_backend', '0003_auto_20201226_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affiliation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='author',
            name='paper',
        ),
        migrations.AddField(
            model_name='paper',
            name='jornal_name',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='PaperAuthorAffiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esra_backend.Affiliation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esra_backend.Author')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esra_backend.Paper')),
            ],
        ),
    ]
