# Generated by Django 2.2.5 on 2020-12-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esra_backend', '0005_auto_20201230_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='jornal_name',
        ),
        migrations.AddField(
            model_name='paper',
            name='journal_name',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
