# Generated by Django 2.2.5 on 2021-02-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esra_backend', '0006_auto_20201231_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='mag_id',
        ),
        migrations.AlterField(
            model_name='paper',
            name='arxiv_id',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='conference',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['arxiv_id'], name='arxiv_idx'),
        ),
    ]
